sonar.projectKey=demo-project
sonar.working.directory=/home/karthiprasad/sonar-demo/.sonarqube/out/.sonar
sonar.projectBaseDir=/home/karthiprasad/sonar-demo
sonar.pullrequest.cache.basepath=/home/karthiprasad/sonar-demo

105B9319-FC81-4067-9A97-F3704A117202.sonar.projectKey=demo-project:105B9319-FC81-4067-9A97-F3704A117202
105B9319-FC81-4067-9A97-F3704A117202.sonar.projectName=sonar-demo
105B9319-FC81-4067-9A97-F3704A117202.sonar.projectBaseDir=/home/karthiprasad/sonar-demo
105B9319-FC81-4067-9A97-F3704A117202.sonar.sourceEncoding=utf-8
105B9319-FC81-4067-9A97-F3704A117202.sonar.tests=
105B9319-FC81-4067-9A97-F3704A117202.sonar.sources=\
"/home/karthiprasad/sonar-demo/Program.cs",\
"/home/karthiprasad/sonar-demo/obj/project.assets.json",\
"/home/karthiprasad/sonar-demo/obj/sonar-demo.csproj.nuget.dgspec.json",\
"/home/karthiprasad/sonar-demo/bin/Debug/net8.0/sonar-demo.runtimeconfig.json",\
"/home/karthiprasad/sonar-demo/bin/Debug/net8.0/sonar-demo.deps.json"

105B9319-FC81-4067-9A97-F3704A117202.sonar.cs.analyzer.projectOutPaths=\
"/home/karthiprasad/sonar-demo/.sonarqube/out/0"
105B9319-FC81-4067-9A97-F3704A117202.sonar.cs.roslyn.reportFilePaths=\
"/home/karthiprasad/sonar-demo/.sonarqube/out/0/Issues.json"
105B9319-FC81-4067-9A97-F3704A117202.sonar.cs.scanner.telemetry=\
"/home/karthiprasad/sonar-demo/.sonarqube/out/0/Telemetry.json"

105B9319-FC81-4067-9A97-F3704A117202.sonar.working.directory=/home/karthiprasad/sonar-demo/.sonarqube/out/.sonar/mod0
sonar.host.url=http://localhost:9000
sonar.pullrequest.key=1
sonar.pullrequest.branch=feature
sonar.pullrequest.base=main
sonar.visualstudio.enable=false

sonar.modules=105B9319-FC81-4067-9A97-F3704A117202

