name: SonarQube

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Install Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add Path
        eun: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Sonar Begin
        run: |
          dotnet sonarscanner begin \
            /k:"demo-console-app" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build
        run: dotnet build

      - name: Sonar End
        run: |
          dotnet sonarscanner end \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      